services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb:Z' # :Z je kljuƒçno za SELinux/Podman dozvole

  moodle:
    image: bitnami/moodle:latest
    # U rootless modu, user: root unutar kontejnera je mapiran na tvog usera spolja
    user: root 
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_REVERSEPROXY=yes
    volumes:
      - 'moodle_data:/bitnami/moodle:Z'
      - './install_plugins.sh:/install_plugins.sh:Z'
    command: /bin/bash -c "/install_plugins.sh && /opt/bitnami/scripts/moodle/run.sh"

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile:Z'
      - 'caddy_data:/data:Z'